/**
 * engine/world-bosses/boss-data.js
 *
 * Фиксированные (не сгенерированные) данные 11 уникальных боссов.
 * hp — это SHARED HP POOL для группового энкаунтера (см. group-encounter.js),
 * не HP одного файтера "как у игрока". Бары прочности/атаки/защиты/скорости
 * с карточек (0-8) переведены в статы combat-engine через RAID-масштаб —
 * они на порядок выше обычных мобов, иначе групповая механика бессмысленна.
 *
 * ПРОВЕРЬ: имена/лор/локации взяты из присланных материалов как есть,
 * сверь с реальным лором Периферии перед вводом в игру.
 */
'use strict';
const P = require('../enemy-skills/skill-primitives.js');

// bar: 0-8 с карточки -> число в диапазоне статов рейд-босса
const bar = (n, cap = 220) => Math.round((n / 8) * cap);

const BOSSES = {
  guardian_unnamed_horizons: {
    name: '«Хранитель Безымянных Горизонтов»',
    subtitle: 'Искажённый смотритель Бездны',
    threatLevel: 'СЛОЖНО', location: 'Бездна Оррин', faction: 'Дети Пятого Голоса (Искажённые)',
    respawn: { type: 'timer', hours: null }, // "неизвестно" на карточке — респавн не гарантирован таймером
    hp: 7000,
    stats: { power: bar(8), mind: bar(8), reaction: bar(4), endurance: bar(8), firepower: bar(8), shielding: bar(7) },
    accuracy: 0.85, dodge: 0.1, focus: 0.8, luck: 12,
    resistances: { kinetic: 0.4, fire: 0.6, poison: 0.3, emp: 0.8, psionic: 0.6 },
    groupSizeExpected: '4+', soloViable: false,
    loot: [
      { id: 'abyss_core_fragment', name: 'Фрагмент ядра Бездны (уникальная валюта)', chance: 25 },
      { id: 'fifth_voice_echo', name: 'Эхо Пятого Голоса', chance: 14 },
      { id: 'distortion_stabilizer', name: 'Искажённый стабилизатор', chance: 12 },
      { id: 'blueprint_horizon_vanish', name: 'Чертёж: «Горизонт исчезновения»', chance: 5 },
      { id: 'singular_crystal', name: 'Сингулярный кристалл', chance: 8 },
      { id: 'quantum_shift_module', name: 'Модуль квантового сдвига', chance: 6 },
      { id: 'deco_eye_of_abyss', name: 'Уникальный декор: «Око Бездны» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'reality_rift', name: 'Разлом реальности', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'distortion', amount: 40, turns: 3 }) },
      { id: 'gravity_collapse', name: 'Гравитационный коллапс', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.statmod(tgt, { stat: 'dodge', mult: 0.4, turns: 3, label: 'Гравитационный коллапс' }) },
      { id: 'fifth_voice_echo_skill', name: 'Эхо Пятого Голоса', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.statmod(tgt, { stat: 'accuracy', mult: 0.5, turns: 2, label: 'Эхо Пятого Голоса' }) },
      { id: 'time_distortion', name: 'Искажение времени', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'reaction', mult: 1.4, turns: 3, label: 'Искажение времени' }) },
      { id: 'void_spheres', name: 'Сферы пустоты', cooldown: 4, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'void', amount: 30, turns: 2 }) },
      { id: 'abyss_awakening', name: 'Пробуждение Бездны', cooldown: 99, trigger: 'hpBelow:0.25', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'power', mult: 1.5, turns: 99, label: 'Пробуждение Бездны' }) },
    ],
  },

  ksarn_praxid: {
    name: '«Ксарнский Праксид»',
    subtitle: 'Воплощённое эхо разрушенной логики',
    threatLevel: 'ЛЕГКО', location: 'Некрополь Ксарн — внутренние залы', faction: 'Забытые',
    respawn: { type: 'timer', hours: 2, window: { startHour: 14, endHour: 16, peakHour: 15 } },
    hp: 1800,
    stats: { power: bar(4), mind: bar(4), reaction: bar(7), endurance: bar(5), firepower: bar(4), shielding: bar(4) },
    accuracy: 0.78, dodge: 0.18, focus: 0.7, luck: 8,
    resistances: { kinetic: 0.2, fire: 0.4, poison: 0.1, emp: 0.8, psionic: -0.25 }, // уязвимость к психонике
    groupSizeExpected: '1-2', soloViable: true,
    aggression: 'neutral', // атакует только при провокации/взаимодействии с терминалами
    loot: [
      { id: 'distorted_protocol_fragment', name: 'Фрагмент искажённого протокола (уникальная валюта)', chance: 25 },
      { id: 'energy_matrix', name: 'Энергетическая матрица', chance: 14 },
      { id: 'keeper_neuro_core', name: 'Нейро-ядро Хранителя', chance: 12 },
      { id: 'blueprint_psi_jammer', name: 'Чертёж: «Модуль пси-помех»', chance: 10 },
      { id: 'phantom_ferrum_alloy', name: 'Сплав «Призрачный феррум»', chance: 6 },
      { id: 'deco_echo_ksarn', name: 'Уникальный декор: «Эхо Ксарна» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'psycho_impulse', name: 'Психо-импульс', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.statmod(tgt, { stat: 'accuracy', mult: 0.6, turns: 2, label: 'Психо-импульс' }) },
      { id: 'scanner_drones', name: 'Дроны-сканеры', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.nextHitBonus(self, { mult: 1.1, label: 'Дроны-сканеры отмечают цель' }) },
      { id: 'logic_fault', name: 'Логический сбой', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.disable(tgt, { turns: 1, label: 'Логический сбой' }) },
      { id: 'phase_jump', name: 'Фазовый скачок', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'echo', amount: 12, turns: 1 }) },
      { id: 'shard_shield', name: 'Осколковый щит', cooldown: 5, trigger: 'hpBelow:0.5', phase: 'rage',
        run: (self) => P.shield(self, { percent: 0.15, turns: 3, label: 'Осколковый щит' }) },
    ],
  },

  forge_archon: {
    name: '«Кузнечный Архонт»',
    subtitle: 'Верный инструмент забытой кузни',
    threatLevel: 'СЛОЖНО', location: 'Кузня Забытых', faction: 'Забытые Кузнецы (Изгнанные)',
    respawn: { type: 'timer', hours: 180 },
    hp: 7000,
    stats: { power: bar(8), mind: bar(6), reaction: bar(3), endurance: bar(8), firepower: bar(8), shielding: bar(6) },
    accuracy: 0.85, dodge: 0.06, focus: 0.75, luck: 10,
    resistances: { kinetic: 0.4, fire: 0.75, poison: 0.2, emp: 0.5, psionic: 0.4 },
    groupSizeExpected: '4+', soloViable: false,
    loot: [
      { id: 'forge_archon_core', name: 'Ядро Кузнечного Архонта (уникальная валюта)', chance: 22 },
      { id: 'siege_protocol_fragment', name: 'Фрагмент осадного протокола', chance: 14 },
      { id: 'thermonuclear_condenser', name: 'Термоядерный конденсатор', chance: 12 },
      { id: 'black_heart_alloy', name: 'Сплав «Чёрное сердце»', chance: 10 },
      { id: 'armor_smelting_module', name: 'Модуль переплавки брони', chance: 8 },
      { id: 'blueprint_fire_hammer', name: 'Чертёж: «Огненный молот»', chance: 6 },
      { id: 'deco_forge_banner', name: 'Уникальный декор: «Знамя Кузни» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'domain_cannon', name: 'Доменная пушка', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'thermal', amount: 45, turns: 2 }) },
      { id: 'smelting', name: 'Переплавление', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'burn', amount: 25, turns: 4 }) },
      { id: 'forge_drones_call', name: 'Вызов кузнечных дронов', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self) => P.statmod(self, { stat: 'power', mult: 1.2, turns: 3, label: 'Вызов кузнечных дронов' }) },
      { id: 'thermal_storm', name: 'Термический шторм', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'thermal', amount: 20, turns: 3 }) },
      { id: 'forge_shield', name: 'Кузнечный щит', cooldown: 6, trigger: 'hpBelow:0.6', phase: 'rage',
        run: (self) => P.shield(self, { percent: 0.35, turns: 3, label: 'Кузнечный щит' }) },
      { id: 'smelting_core', name: 'Ядро плавки', cooldown: 99, trigger: 'hpBelow:0.25', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 1.6, turns: 99, label: 'Ядро плавки' }) },
    ],
  },

  ksarn_memorist: {
    name: '«Ксарнский Меморист»',
    subtitle: 'Хранитель забытых летописей',
    threatLevel: 'СЛОЖНО', location: 'Некрополь Ксарн', faction: 'Ксарнский Домен (Искажённые)',
    respawn: { type: 'timer', hours: null },
    hp: 7000,
    stats: { power: bar(8), mind: bar(8), reaction: bar(3), endurance: bar(8), firepower: bar(7), shielding: bar(7) },
    accuracy: 0.85, dodge: 0.06, focus: 0.85, luck: 10,
    resistances: { kinetic: 0.4, fire: 0.55, poison: 0.3, emp: 0.8, psionic: 0.2 },
    groupSizeExpected: '4+', soloViable: false,
    loot: [
      { id: 'memorist_core', name: 'Ядро Мемориста (уникальная валюта)', chance: 20 },
      { id: 'ksarn_chronicle_fragment', name: 'Фрагмент летописи Ксарн', chance: 14 },
      { id: 'memory_crystal', name: 'Кристалл памяти', chance: 12 },
      { id: 'blueprint_chrono_editor', name: 'Чертёж: «Хроно-редактор»', chance: 10 },
      { id: 'neuro_archive_module', name: 'Нейро-архивный модуль', chance: 8 },
      { id: 'oblivion_alloy', name: 'Сплав «Забвение»', chance: 6 },
      { id: 'deco_ksarn_page', name: 'Уникальный декор: «Страница Ксарн» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'chrono_tear', name: 'Хронический разрыв', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'chrono', amount: 30, turns: 3 }) },
      { id: 'memory_extraction', name: 'Изъятие памяти', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.disable(tgt, { turns: 1, label: 'Изъятие памяти' }) },
      { id: 'archive_beam', name: 'Архивный луч', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self) => P.nextHitBonus(self, { mult: 1.5, label: 'Архивный луч' }) },
      { id: 'summon_chroniclers', name: 'Призыв летописцев', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 1.25, turns: 3, label: 'Призыв летописцев' }) },
      { id: 'gravity_verse', name: 'Гравитационный стих', cooldown: 4, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'gravity', amount: 22, turns: 3 }) },
      { id: 'archive_leap', name: 'Архивный скачок', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self) => P.hot(self, { amount: 100, turns: 2 }) },
    ],
  },

  echo_destroyer: {
    name: '«Эхо-Разрушитель»',
    subtitle: 'Реликт войны без команды',
    threatLevel: 'ВЫСОКИЙ', location: 'Кладбище Флота', faction: 'Нейтральные Тени (без принадлежности)',
    respawn: { type: 'timer', hours: 72 },
    hp: 5000,
    stats: { power: bar(7), mind: bar(5), reaction: bar(2), endurance: bar(8), firepower: bar(7), shielding: bar(5) },
    accuracy: 0.82, dodge: 0.04, focus: 0.7, luck: 8,
    resistances: { kinetic: 0.6, fire: 0.35, poison: 0.2, emp: 0.8, psionic: 0.3 },
    groupSizeExpected: '3-4', soloViable: false,
    loot: [
      { id: 'relic_core_complex', name: 'Реликтовый ядро-комплекс (уникальная валюта)', chance: 20 },
      { id: 'combat_protocol_fragment', name: 'Фрагмент боевого протокола', chance: 12 },
      { id: 'gravidrive_stabilizer', name: 'Стабилизатор грави-двигателя', chance: 10 },
      { id: 'titanium_armor_debris', name: 'Обломки титановой брони', chance: 12 },
      { id: 'battleship_energy_cell', name: 'Энергоячейка линкора', chance: 8 },
      { id: 'blueprint_echo_gun', name: 'Чертёж: «Эхо-пушка»', chance: 3 },
      { id: 'deco_echo_of_war', name: 'Уникальный декор: «Эхо войны» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'echo_salvo', name: 'Эхо залп', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'kinetic', amount: 35, turns: 2 }) },
      { id: 'debris_absorption', name: 'Поглощение обломков', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.shield(self, { percent: 0.2, turns: 3, label: 'Поглощение обломков' }) },
      { id: 'gravity_rupture', name: 'Гравитационный разрыв', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'gravity', amount: 20, turns: 3 }) },
      { id: 'protocol_reboot', name: 'Перезагрузка протоколов', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.disable(tgt, { turns: 1, label: 'Перезагрузка протоколов' }) },
      { id: 'last_order', name: 'Последний приказ', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 2.0, turns: 99, label: 'Последний приказ' }) },
    ],
  },

  oblivion_engineer: {
    name: '«Инженер Забвения»',
    subtitle: 'Последний кузнец Легиона Гелиоса',
    threatLevel: 'ВЫСОЧАЙШИЙ', location: 'Кузня Забытых', faction: 'Легион Гелиоса (Изгнанные)',
    respawn: { type: 'timer', hours: 120 },
    hp: 9000,
    stats: { power: bar(8), mind: bar(6), reaction: bar(4), endurance: bar(8), firepower: bar(8), shielding: bar(7) },
    accuracy: 0.88, dodge: 0.08, focus: 0.8, luck: 12,
    resistances: { kinetic: 0.4, fire: 0.7, poison: 0.2, emp: 0.7, psionic: 0.3 },
    groupSizeExpected: '5+', soloViable: false,
    loot: [
      { id: 'smelting_furnace_core', name: 'Ядро плавильной печи (уникальная валюта)', chance: 22 },
      { id: 'legion_codex_fragment', name: 'Фрагмент кодекса Легиона', chance: 14 },
      { id: 'blueprint_thermal_core', name: 'Чертёж: «Термическое ядро»', chance: 10 },
      { id: 'smelting_condenser', name: 'Плавильный конденсатор', chance: 11 },
      { id: 'energy_redistribution_module', name: 'Модуль перераспределения энергии', chance: 8 },
      { id: 'helios_x_alloy', name: 'Редкий сплав «Гелиос-Х»', chance: 7 },
      { id: 'deco_oblivion_seal', name: 'Уникальный декор: «Печать Забвения» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'smelting_verdict', name: 'Плавильный приговор', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'thermal', amount: 50, turns: 3 }) },
      { id: 'forge_summon', name: 'Кузнечный призыв', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 1.3, turns: 3, label: 'Кузнечный призыв' }) },
      { id: 'core_overheat', name: 'Перегрев ядра', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.statmod(self, { stat: 'power', mult: 1.3, turns: 2, label: 'Перегрев ядра' }) },
      { id: 'chain_grab', name: 'Цепной захват', cooldown: 4, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.disable(tgt, { turns: 1, label: 'Цепной захват' }) },
      { id: 'production_mode', name: 'Производственный режим', cooldown: 5, trigger: 'hpBelow:0.5', phase: 'rage',
        run: (self) => P.shield(self, { percent: 0.3, turns: 3, label: 'Производственный режим' }) },
      { id: 'self_cleaning', name: 'Самоочищение', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self) => P.hot(self, { amount: 120, turns: 2 }) },
    ],
  },

  shadow_auctioneer: {
    name: '«Теневой Аукционер»',
    subtitle: 'Хранитель рынка без правил',
    threatLevel: 'СРЕДНИЙ', location: 'Ярмарка Теней — Центральный купол аукциона', faction: 'Ярмарка Теней',
    respawn: { type: 'timer', hours: 24 },
    hp: 3000,
    stats: { power: bar(7), mind: bar(7), reaction: bar(4), endurance: bar(7), firepower: bar(6), shielding: bar(6) },
    accuracy: 0.8, dodge: 0.12, focus: 0.75, luck: 9,
    resistances: { kinetic: 0.35, fire: 0.4, poison: 0.4, emp: 0.7, psionic: 0.3 },
    groupSizeExpected: '2-3', soloViable: false,
    aggression: 'passive', // враждебен только при краже/атаке торговцев
    loot: [
      { id: 'shadow_market_token', name: 'Жетон теневого рынка (уникальная валюта)', chance: 22 },
      { id: 'blueprint_hidden_bay', name: 'Чертёж: «Скрытый отсек»', chance: 8 },
      { id: 'stealth_module_mk3', name: 'Модуль маскировки Mk.3', chance: 6 },
      { id: 'trakt_energy_cell', name: 'Энергоячейка Тракта', chance: 4 },
      { id: 'market_protocol_fragment', name: 'Фрагмент протокола рынка (коллекционный)', chance: 10 },
      { id: 'deco_auctioneer_sign', name: 'Уникальный декор: «Знак Аукционера» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'pain_auction', name: 'Аукцион боли', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'debt', amount: 20, turns: 3 }) },
      { id: 'bid_lock', name: 'Блокировка торгов', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.disable(tgt, { turns: 1, label: 'Блокировка торгов' }) },
      { id: 'call_guards', name: 'Вызов охраны', cooldown: 6, trigger: 'hpBelow:0.6', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'power', mult: 1.25, turns: 3, label: 'Вызов охраны' }) },
      { id: 'appraisal', name: 'Оценка товара', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.nextHitBonus(self, { mult: 1.3, label: 'Оценка товара' }) },
    ],
  },

  void_keeper: {
    name: '«Хранитель Пустоты»',
    subtitle: 'Страж забытого ордена',
    threatLevel: 'ВЫСОКИЙ', location: 'Кладбище Флота', faction: 'Осколки Ордена Пустоты',
    respawn: { type: 'timer', hours: 96 },
    hp: 5000,
    stats: { power: bar(7), mind: bar(7), reaction: bar(4), endurance: bar(8), firepower: bar(7), shielding: bar(7) },
    accuracy: 0.83, dodge: 0.08, focus: 0.8, luck: 10,
    resistances: { kinetic: 0.4, fire: 0.55, poison: 0.2, emp: 0.7, psionic: 0.4 },
    groupSizeExpected: '3-4', soloViable: false,
    loot: [
      { id: 'void_core', name: 'Ядро Пустоты (уникальная валюта)', chance: 18 },
      { id: 'void_codex_fragment', name: 'Фрагмент кодекса Пустоты', chance: 12 },
      { id: 'singularity_field_shard', name: 'Осколок сингулярного поля', chance: 11 },
      { id: 'time_distortion_module', name: 'Модуль искажения времени', chance: 9 },
      { id: 'transition_stabilizer', name: 'Стабилизатор перехода', chance: 7 },
      { id: 'blueprint_void_beam', name: 'Чертёж: «Пустотный луч»', chance: 3 },
      { id: 'deco_void_sign', name: 'Уникальный декор: «Знак Пустоты» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'void_beam', name: 'Пустотный луч', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self) => P.nextHitBonus(self, { mult: 1.4, label: 'Пустотный луч' }) },
      { id: 'shard_summon', name: 'Призыв осколков', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 1.2, turns: 3, label: 'Призыв осколков' }) },
      { id: 'annihilation_wave', name: 'Аннигиляционная волна', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.statmod(tgt, { stat: 'reaction', mult: 0.6, turns: 2, label: 'Аннигиляционная волна' }) },
      { id: 'singularity_field', name: 'Сингулярное поле', cooldown: 4, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'gravity', amount: 22, turns: 3 }) },
      { id: 'reality_reload', name: 'Перезагрузка реальности', cooldown: 6, trigger: 'hpBelow:0.5', phase: 'rage',
        run: (self) => P.shield(self, { percent: 0.5, turns: 2, label: 'Перезагрузка реальности' }) },
      { id: 'order_fall', name: 'Падение Ордена', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'void', amount: 60, turns: 2 }) },
    ],
  },

  abyss_firstborn: {
    name: '«Перворождённая Бездны»',
    subtitle: 'Эхо Пятого Голоса',
    threatLevel: 'СЛОЖНО', location: 'Бездна Оррин', faction: 'Эхо Пятого Голоса (Искажённые)',
    respawn: { type: 'timer', hours: null },
    hp: 7000,
    stats: { power: bar(8), mind: bar(7), reaction: bar(4), endurance: bar(8), firepower: bar(7), shielding: bar(7) },
    accuracy: 0.86, dodge: 0.08, focus: 0.85, luck: 12,
    resistances: { kinetic: 0.4, fire: 0.65, poison: 0.3, emp: 0.8, psionic: 0.1 },
    groupSizeExpected: '4+', soloViable: false,
    loot: [
      { id: 'abyss_core_fragment_2', name: 'Фрагмент ядра Бездны (уникальная валюта)', chance: 24 },
      { id: 'voice_echo_matrix', name: 'Эхо-матрица Голоса', chance: 14 },
      { id: 'distorted_stabilizer', name: 'Искажённый стабилизатор', chance: 12 },
      { id: 'impossible_alloy', name: 'Сплав невозможного', chance: 10 },
      { id: 'blueprint_horizon_vanish_2', name: 'Чертёж: «Горизонт исчезновения»', chance: 5 },
      { id: 'energy_parasite', name: 'Энергетический паразит', chance: 5 },
      { id: 'deco_void_calls', name: 'Уникальный декор: «Пустота зовёт» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'voice_from_abyss', name: 'Голос из Бездны', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.statmod(tgt, { stat: 'accuracy', mult: 0.6, turns: 2, label: 'Голос из Бездны' }) },
      { id: 'reality_tear', name: 'Разрыв реальности', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'distortion', amount: 45, turns: 2 }) },
      { id: 'energy_absorption', name: 'Абсорбция энергии', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.hot(self, { amount: 40, turns: 3 }) },
      { id: 'summon_distorted', name: 'Призыв искажённых', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'firepower', mult: 1.25, turns: 3, label: 'Призыв искажённых' }) },
      { id: 'sector_collapse', name: 'Коллапс сектора', cooldown: 6, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'void', amount: 30, turns: 3 }) },
      { id: 'abyss_recovery', name: 'Восстановление через Бездну', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self) => P.hot(self, { amount: 150, turns: 3 }) },
    ],
  },

  ksarn_echo_keeper: {
    name: '«Эхо Хранитель Ксарн»',
    subtitle: 'Страж забытого договора',
    threatLevel: 'СРЕДНИЙ', location: 'Некрополь Ксарн', faction: 'Хранители Договора (Искажённые)',
    respawn: { type: 'timer', hours: 6, window: { startHour: 2, endHour: 4, peakHour: 3 } },
    hp: 3000,
    stats: { power: bar(8), mind: bar(8), reaction: bar(4), endurance: bar(8), firepower: bar(6), shielding: bar(7) },
    accuracy: 0.84, dodge: 0.08, focus: 0.82, luck: 10,
    resistances: { kinetic: 0.4, fire: 0.5, poison: 0.2, emp: 0.7, psionic: 0.3 },
    groupSizeExpected: '2-3', soloViable: false,
    aggression: 'neutral', // не атакует первым; агрится при приближении к реликтовым коллекциям
    loot: [
      { id: 'ksarn_treaty_shard', name: 'Осколок Договора Ксарн (уникальная валюта)', chance: 22 },
      { id: 'keeper_fragment', name: 'Фрагмент Хранителя', chance: 14 },
      { id: 'relic_battery', name: 'Реликтовая батарея', chance: 12 },
      { id: 'blueprint_chrono_barrier', name: 'Чертёж: «Хроно-барьер»', chance: 10 },
      { id: 'archive_guard_core', name: 'Ядро архивного стража', chance: 8 },
      { id: 'eternal_oath_alloy', name: 'Сплав «Вечная клятва»', chance: 6 },
      { id: 'deco_ksarn_seal', name: 'Уникальный декор: «Печать Ксарн» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'chrono_rewind', name: 'Хрональный откат', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self) => P.hot(self, { amount: 50, turns: 1 }) },
      { id: 'archive_barrier', name: 'Архивный барьер', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.shield(self, { percent: 0.7, turns: 1, label: 'Архивный барьер' }) },
      { id: 'memory_trial', name: 'Суд памяти', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'psionic', amount: 25, turns: 2 }) },
      { id: 'time_decay', name: 'Распад времени', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.statmod(tgt, { stat: 'reaction', mult: 0.4, turns: 2, label: 'Распад времени' }) },
      { id: 'keeper_summon', name: 'Хранительный призыв', cooldown: 6, trigger: 'hpBelow:0.6', phase: 'rage',
        run: (self) => P.statmod(self, { stat: 'power', mult: 1.2, turns: 3, label: 'Хранительный призыв' }) },
      { id: 'treaty_seal', name: 'Договорная печать', cooldown: 99, trigger: 'hpBelow:0.2', phase: 'rage',
        run: (self) => P.shield(self, { percent: 1.0, turns: 2, label: 'Договорная печать' }) },
    ],
  },

  vexar_chronofallen: {
    name: '«Хронопадальщик Вексар»',
    subtitle: 'Искажение из забытой эры',
    threatLevel: 'ВЫСОКИЙ', location: 'Кладбище Флота', faction: 'Искажённый клан Вексар',
    respawn: { type: 'timer', hours: 88 },
    hp: 5000,
    stats: { power: bar(7), mind: bar(7), reaction: bar(2), endurance: bar(8), firepower: bar(7), shielding: bar(6) },
    accuracy: 0.83, dodge: 0.04, focus: 0.78, luck: 9,
    resistances: { kinetic: 0.3, fire: 0.4, poison: 0.3, emp: 0.7, psionic: 0.2 },
    groupSizeExpected: '3-4', soloViable: false,
    loot: [
      { id: 'chrono_core_fragment', name: 'Фрагмент хроноядра (уникальная валюта)', chance: 22 },
      { id: 'distorted_chrono_module', name: 'Искажённый хрономодуль', chance: 14 },
      { id: 'ancient_alloy_shell', name: 'Оболочка из древнего сплава', chance: 12 },
      { id: 'time_field_stabilizer', name: 'Стабилизатор временного поля', chance: 10 },
      { id: 'blueprint_chrono_impulse', name: 'Чертёж: «Хроно-импульс»', chance: 6 },
      { id: 'vexar_energy_cell', name: 'Энергоячейка Вексар', chance: 4 },
      { id: 'deco_fall_symbol', name: 'Уникальный декор: «Символ падения» (для корабля)', chance: 3 },
    ],
    skills: [
      { id: 'chronorift', name: 'Хроноразрыв', cooldown: 3, trigger: 'always', phase: 'normal',
        run: (self, tgt) => P.dot(tgt, { kind: 'chrono', amount: 32, turns: 2 }) },
      { id: 'reality_rewind', name: 'Перемотка реальности', cooldown: 5, trigger: 'always', phase: 'normal',
        run: (self) => P.hot(self, { amount: 45, turns: 1 }) },
      { id: 'time_harvest', name: 'Сбор времени', cooldown: 4, trigger: 'always', phase: 'normal',
        run: (self) => P.statmod(self, { stat: 'shielding', mult: 1.2, turns: 3, label: 'Сбор времени' }) },
      { id: 'chronokinetic_spears', name: 'Хронокинетические копья', cooldown: 3, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'kinetic', amount: 38, turns: 2 }) },
      { id: 'era_distortion', name: 'Искажение эпох', cooldown: 5, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.dot(tgt, { kind: 'chrono', amount: 20, turns: 3 }) },
      { id: 'decay_aura', name: 'Аура распада', cooldown: 1, trigger: 'always', phase: 'rage',
        run: (self, tgt) => P.statmod(tgt, { stat: 'dodge', mult: 0.9, turns: 1, label: 'Аура распада' }) },
    ],
  },
};

module.exports = { BOSSES, bar };
