'use strict';

const PVP_LIMITS = {
  WINNER_REPUTATION: 15,
  WINNER_CREDITS: 100,
};

const PVP_ERRORS = {
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  CANNOT_CHALLENGE_SELF: 'CANNOT_CHALLENGE_SELF',
  ALREADY_IN_DUEL: 'ALREADY_IN_DUEL',
  DUEL_NOT_FOUND: 'DUEL_NOT_FOUND',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  DUEL_FINISHED: 'DUEL_FINISHED',
  UNKNOWN_SKILL: 'UNKNOWN_SKILL',
};

module.exports = { PVP_LIMITS, PVP_ERRORS };
