'use strict';

const GUILD_LIMITS = {
  MAX_MEMBERS: 20,
  MAX_NAME_LENGTH: 24,
  MIN_NAME_LENGTH: 3,
  CREATE_COST_CREDITS: 500,
  DONATION_MIN: 1,
};

const GUILD_ROLES = {
  LEADER: 'leader',
  OFFICER: 'officer',
  MEMBER: 'member',
};

const GUILD_ERRORS = {
  NAME_TAKEN: 'NAME_TAKEN',
  NAME_INVALID: 'NAME_INVALID',
  ALREADY_IN_GUILD: 'ALREADY_IN_GUILD',
  NOT_IN_GUILD: 'NOT_IN_GUILD',
  GUILD_NOT_FOUND: 'GUILD_NOT_FOUND',
  GUILD_FULL: 'GUILD_FULL',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  NOT_LEADER: 'NOT_LEADER',
  NOT_OFFICER_OR_LEADER: 'NOT_OFFICER_OR_LEADER',
  CANNOT_KICK_SELF: 'CANNOT_KICK_SELF',
  LEADER_MUST_TRANSFER: 'LEADER_MUST_TRANSFER',
};

module.exports = { GUILD_LIMITS, GUILD_ROLES, GUILD_ERRORS };
